package com.portfoliomanager.repository;

import com.portfoliomanager.model.ExchangeRate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(ExchangeRateRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class ExchangeRateRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ExchangeRateRepository repository;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS exchange_rates");
        jdbcTemplate.execute("""
                CREATE TABLE exchange_rates (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    currency_code VARCHAR(3) NOT NULL UNIQUE,
                    rate_to_base DECIMAL(20,8) NOT NULL,
                    updated_at TIMESTAMP
                )
                """);
    }

    @Test
    void findAll_returnsRatesSortedByCurrencyCode() {
        insertRate("USD", "83.12000000");
        insertRate("EUR", "90.55000000");
        insertRate("AUD", "54.32000000");

        List<ExchangeRate> all = repository.findAll(null);

        assertEquals(3, all.size());
        assertEquals("AUD", all.get(0).getCurrencyCode());
        assertEquals("EUR", all.get(1).getCurrencyCode());
        assertEquals("USD", all.get(2).getCurrencyCode());
    }

    @Test
    void findByCurrencyCode_returnsExistingAndEmptyForMissing() {
        insertRate("USD", "83.12000000");

        ExchangeRate existing = repository.findByCurrencyCode(1L,"USD").orElseThrow();

        assertEquals("USD", existing.getCurrencyCode());
        assertEquals(0, new BigDecimal("83.12000000").compareTo(existing.getRateToBase()));
        assertTrue(repository.findByCurrencyCode(1L,"JPY").isEmpty());
    }

    @Test
    void upsert_insertsWhenCurrencyDoesNotExist() {
        ExchangeRate saved = repository.upsert(1L, "GBP", new BigDecimal("104.55000000"));

        assertEquals("GBP", saved.getCurrencyCode());
        assertEquals(0, new BigDecimal("104.55000000").compareTo(saved.getRateToBase()));
        assertEquals(1, countRows());
    }

    @Test
    void upsert_updatesWhenCurrencyExists() {
        insertRate("USD", "83.12000000");

        ExchangeRate updated = repository.upsert(1L, "USD", new BigDecimal("84.22000000"));

        assertEquals("USD", updated.getCurrencyCode());
        assertEquals(0, new BigDecimal("84.22000000").compareTo(updated.getRateToBase()));
        assertEquals(1, countRows());
    }

    private void insertRate(String code, String rate) {
        jdbcTemplate.update("""
                INSERT INTO exchange_rates (currency_code, rate_to_base, updated_at)
                VALUES (?, ?, ?)
                """,
                code,
                new BigDecimal(rate),
                null);
    }

    private int countRows() {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM exchange_rates", Integer.class);
        return count == null ? 0 : count;
    }
}
