package com.portfoliomanager.repository;

import com.portfoliomanager.model.ExchangeRate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest(properties = "spring.flyway.enabled=false")
@Import(ExchangeRateRepository.class)
class ExchangeRateRepositoryIntegrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ExchangeRateRepository exchangeRateRepository;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS exchange_rates");
        jdbcTemplate.execute("""
                CREATE TABLE exchange_rates (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    currency_code VARCHAR(3) NOT NULL UNIQUE,
                    rate_to_base DECIMAL(20,8) NOT NULL,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void upsert_insertsWhenCurrencyDoesNotExist() {
        ExchangeRate saved = exchangeRateRepository.upsert("USD", new BigDecimal("83.12000000"));

        assertEquals("USD", saved.getCurrencyCode());
        assertEquals(new BigDecimal("83.12000000"), saved.getRateToBase());
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM exchange_rates WHERE currency_code='USD'",
                Integer.class);
        assertEquals(1, count);
    }

    @Test
    void upsert_updatesWhenCurrencyExists() {
        jdbcTemplate.update("INSERT INTO exchange_rates(currency_code, rate_to_base, updated_at) VALUES (?,?,?)",
                "USD", new BigDecimal("80.00000000"), java.sql.Timestamp.valueOf("2026-08-01 00:00:00"));

        ExchangeRate updated = exchangeRateRepository.upsert("USD", new BigDecimal("81.50000000"));

        assertEquals("USD", updated.getCurrencyCode());
        assertEquals(new BigDecimal("81.50000000"), updated.getRateToBase());
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM exchange_rates WHERE currency_code='USD'",
                Integer.class);
        assertEquals(1, count);
    }

    @Test
    void findByCurrencyCode_andFindAll_returnMappedAndSortedData() {
        jdbcTemplate.update("INSERT INTO exchange_rates(currency_code, rate_to_base, updated_at) VALUES (?,?,?)",
                "USD", new BigDecimal("80.00000000"), java.sql.Timestamp.valueOf("2026-08-01 00:00:00"));
        jdbcTemplate.update("INSERT INTO exchange_rates(currency_code, rate_to_base, updated_at) VALUES (?,?,?)",
                "EUR", new BigDecimal("90.00000000"), java.sql.Timestamp.valueOf("2026-08-01 00:00:00"));

        Optional<ExchangeRate> eur = exchangeRateRepository.findByCurrencyCode("EUR");
        List<ExchangeRate> all = exchangeRateRepository.findAll();

        assertTrue(eur.isPresent());
        assertEquals(new BigDecimal("90.00000000"), eur.get().getRateToBase());
        assertEquals(2, all.size());
        assertEquals("EUR", all.get(0).getCurrencyCode());
        assertEquals("USD", all.get(1).getCurrencyCode());
    }
}
