package com.portfoliomanager.repository;

import com.portfoliomanager.mapper.InvestmentRowMapper;
import com.portfoliomanager.model.Investment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertSame;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class InvestmentRepositoryTest {

    @Mock
    private JdbcTemplate jdbcTemplate;

    @InjectMocks
    private InvestmentRepository investmentRepository;

    @Test
    void findAllActive_usesActiveFilterQuery() {
        List<Investment> expected = List.of(Investment.builder().id(1L).build());

        when(jdbcTemplate.query(eq("SELECT * FROM investments WHERE status = 'ACTIVE'"),
                any(InvestmentRowMapper.class)))
                .thenReturn(expected);

        List<Investment> result = investmentRepository.findAllActive();

        assertSame(expected, result);
        verify(jdbcTemplate).query(eq("SELECT * FROM investments WHERE status = 'ACTIVE'"),
                any(InvestmentRowMapper.class));
import com.portfoliomanager.model.Investment;
import com.portfoliomanager.model.InvestmentStatus;
import com.portfoliomanager.model.InvestmentType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(InvestmentRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class InvestmentRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private InvestmentRepository repository;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS investments");
        jdbcTemplate.execute("""
                CREATE TABLE investments (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type VARCHAR(10) NOT NULL,
                    symbol VARCHAR(30) NOT NULL,
                    name VARCHAR(150) NOT NULL,
                    country VARCHAR(50) NOT NULL,
                    currency VARCHAR(3) NOT NULL,
                    quantity DECIMAL(20,6),
                    avg_buy_price DECIMAL(20,6),
                    current_price DECIMAL(20,6),
                    invested_amount DECIMAL(20,6) NOT NULL DEFAULT 0,
                    current_value DECIMAL(20,6) NOT NULL DEFAULT 0,
                    previous_value DECIMAL(20,6),
                    interest_rate DECIMAL(6,3),
                    maturity_date DATE,
                    purchase_date DATE,
                    status VARCHAR(10) NOT NULL,
                    notes VARCHAR(255),
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
    }

    @Test
    void saveAndFindById_roundTripPersistsCoreFields() {
        Investment inv = sampleInvestment(InvestmentType.STOCK, "AAPL", "US", InvestmentStatus.ACTIVE);

        Investment saved = repository.save(inv);

        assertTrue(saved.getId() > 0);
        assertEquals("AAPL", saved.getSymbol());
        assertEquals(new BigDecimal("1000.000000"), saved.getInvestedAmount());
        assertEquals(new BigDecimal("1100.000000"), saved.getCurrentValue());
    }

    @Test
    void findAll_appliesTypeCountryStatusFilters() {
        insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1100.000000");
        insertInvestmentRow("TCS", "India", "STOCK", "ACTIVE", "1000.000000", "1100.000000");
        insertInvestmentRow("QQQ", "US", "ETF", "CLOSED", "1000.000000", "1100.000000");

        List<Investment> result = repository.findAll(InvestmentType.STOCK, "US", InvestmentStatus.ACTIVE);

        assertEquals(1, result.size());
        assertEquals("AAPL", result.get(0).getSymbol());
    }

    @Test
    void findAllActive_returnsOnlyActiveRows() {
        insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1100.000000");
        insertInvestmentRow("QQQ", "US", "ETF", "CLOSED", "1000.000000", "1100.000000");

        List<Investment> active = repository.findAllActive();

        assertEquals(1, active.size());
        assertEquals("AAPL", active.get(0).getSymbol());
    }

    @Test
    void update_overwritesEditableColumns() {
        long id = insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1100.000000");
        Investment existing = repository.findById(id).orElseThrow();
        existing.setName("Apple Updated");
        existing.setCountry("UK");
        existing.setNotes("updated");
        existing.setCurrency("GBP");

        Investment updated = repository.update(existing);

        assertEquals("Apple Updated", updated.getName());
        assertEquals("UK", updated.getCountry());
        assertEquals("GBP", updated.getCurrency());
        assertEquals("updated", updated.getNotes());
    }

    @Test
    void updatePrice_updatesPriceAndCurrentValue() {
        long id = insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1100.000000");

        repository.updatePrice(id, new BigDecimal("150.000000"), new BigDecimal("1500.000000"));

        Investment refreshed = repository.findById(id).orElseThrow();
        assertEquals(new BigDecimal("150.000000"), refreshed.getCurrentPrice());
        assertEquals(new BigDecimal("1500.000000"), refreshed.getCurrentValue());
    }

    @Test
    void rollCurrentValueIntoPrevious_onlyForActiveRows() {
        long activeId = insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1300.000000");
        long closedId = insertInvestmentRow("QQQ", "US", "ETF", "CLOSED", "1000.000000", "1400.000000");

        repository.rollCurrentValueIntoPrevious();

        Investment active = repository.findById(activeId).orElseThrow();
        Investment closed = repository.findById(closedId).orElseThrow();
        assertEquals(active.getCurrentValue(), active.getPreviousValue());
        assertFalse(closed.getCurrentValue().compareTo(closed.getPreviousValue()) == 0);
    }

    @Test
    void deleteById_returnsTrueWhenDeletedAndFalseWhenMissing() {
        long id = insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1100.000000");

        assertTrue(repository.deleteById(id));
        assertFalse(repository.deleteById(id));
    }

    @Test
    void existsById_reportsPresenceCorrectly() {
        long id = insertInvestmentRow("AAPL", "US", "STOCK", "ACTIVE", "1000.000000", "1100.000000");

        assertTrue(repository.existsById(id));
        assertFalse(repository.existsById(id + 100));
    }

    private Investment sampleInvestment(InvestmentType type, String symbol, String country, InvestmentStatus status) {
        return Investment.builder()
                .type(type)
                .symbol(symbol)
                .name("Sample")
                .country(country)
                .currency("USD")
                .quantity(new BigDecimal("10.000000"))
                .avgBuyPrice(new BigDecimal("100.000000"))
                .currentPrice(new BigDecimal("110.000000"))
                .investedAmount(new BigDecimal("1000.000000"))
                .currentValue(new BigDecimal("1100.000000"))
                .previousValue(new BigDecimal("900.000000"))
                .interestRate(new BigDecimal("0.000"))
                .maturityDate(LocalDate.of(2030, 1, 1))
                .purchaseDate(LocalDate.of(2024, 1, 1))
                .status(status)
                .notes("notes")
                .build();
    }

    private long insertInvestmentRow(String symbol,
                                     String country,
                                     String type,
                                     String status,
                                     String invested,
                                     String current) {
        jdbcTemplate.update("""
                INSERT INTO investments
                (type, symbol, name, country, currency, quantity, avg_buy_price, current_price,
                 invested_amount, current_value, previous_value, interest_rate, maturity_date,
                 purchase_date, status, notes)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                type, symbol, symbol + " Name", country, "USD",
                new BigDecimal("10.000000"), new BigDecimal("100.000000"), new BigDecimal("110.000000"),
                new BigDecimal(invested), new BigDecimal(current), new BigDecimal("900.000000"),
                new BigDecimal("0.000"), LocalDate.of(2030, 1, 1), LocalDate.of(2024, 1, 1), status, "notes");

        Long id = jdbcTemplate.queryForObject("SELECT MAX(id) FROM investments", Long.class);
        return id == null ? -1 : id;
    }
}
