package com.portfoliomanager.repository;

import com.portfoliomanager.model.Investment;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@JdbcTest(properties = "spring.flyway.enabled=false")
@Import(InvestmentRepository.class)
class InvestmentRepositoryIntegrationTest {

    private static final Long USER_ID = 1L;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private InvestmentRepository investmentRepository;

    @BeforeEach
    void setUpSchemaAndData() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS investments");
        jdbcTemplate.execute("""
                CREATE TABLE investments (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    type VARCHAR(10) NOT NULL,
                    symbol VARCHAR(30) NOT NULL,
                    name VARCHAR(150) NOT NULL,
                    country VARCHAR(50) NOT NULL,
                    currency VARCHAR(3) NOT NULL,
                    quantity DECIMAL(20,6) NULL,
                    avg_buy_price DECIMAL(20,6) NULL,
                    current_price DECIMAL(20,6) NULL,
                    invested_amount DECIMAL(20,6) NOT NULL,
                    current_value DECIMAL(20,6) NOT NULL,
                    previous_value DECIMAL(20,6) NULL,
                    interest_rate DECIMAL(6,3) NULL,
                    maturity_date DATE NULL,
                    purchase_date DATE NULL,
                    status VARCHAR(10) NOT NULL,
                    notes VARCHAR(255) NULL,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO investments (
                    user_id, type, symbol, name, country, currency, quantity, avg_buy_price, current_price,
                    invested_amount, current_value, previous_value, interest_rate, maturity_date,
                    purchase_date, status, notes, created_at, updated_at
                ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                USER_ID, "STOCK", "AAPL", "Apple Inc", "US", "USD", new BigDecimal("10.000000"),
                new BigDecimal("100.000000"), new BigDecimal("120.000000"), new BigDecimal("1000.000000"),
                new BigDecimal("1200.000000"), new BigDecimal("1180.000000"), null, null, null,
                "ACTIVE", "active investment", java.sql.Timestamp.valueOf("2026-08-01 10:00:00"),
                java.sql.Timestamp.valueOf("2026-08-01 10:00:00"));

        jdbcTemplate.update("""
                INSERT INTO investments (
                    user_id, type, symbol, name, country, currency, quantity, avg_buy_price, current_price,
                    invested_amount, current_value, previous_value, interest_rate, maturity_date,
                    purchase_date, status, notes, created_at, updated_at
                ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                USER_ID, "ETF", "NIFTYBEES", "Nifty Bees", "India", "INR", new BigDecimal("5.000000"),
                new BigDecimal("500.000000"), new BigDecimal("490.000000"), new BigDecimal("2500.000000"),
                new BigDecimal("2450.000000"), new BigDecimal("2460.000000"), null, null, null,
                "CLOSED", "closed investment", java.sql.Timestamp.valueOf("2026-08-02 10:00:00"),
                java.sql.Timestamp.valueOf("2026-08-02 10:00:00"));
    }

    @Test
    void findAllActive_returnsOnlyActiveInvestmentsWithMappedFields() {
        List<Investment> active = investmentRepository.findAllActive(USER_ID);

        assertEquals(1, active.size());
        Investment investment = active.get(0);
        assertEquals("AAPL", investment.getSymbol());
        assertEquals("US", investment.getCountry());
        assertEquals("USD", investment.getCurrency());
        assertEquals(new BigDecimal("1000.000000"), investment.getInvestedAmount());
        assertEquals(new BigDecimal("1200.000000"), investment.getCurrentValue());
        assertEquals(new BigDecimal("1180.000000"), investment.getPreviousValue());
    }

    @Test
    void rollCurrentValueIntoPrevious_updatesOnlyActiveInvestments() {
        investmentRepository.rollCurrentValueIntoPrevious(USER_ID);

        BigDecimal activePrevious = jdbcTemplate.queryForObject(
                "SELECT previous_value FROM investments WHERE symbol = 'AAPL'", BigDecimal.class);
        BigDecimal closedPrevious = jdbcTemplate.queryForObject(
                "SELECT previous_value FROM investments WHERE symbol = 'NIFTYBEES'", BigDecimal.class);

        assertEquals(new BigDecimal("1200.000000"), activePrevious);
        assertEquals(new BigDecimal("2460.000000"), closedPrevious);
    }
}
