package com.portfoliomanager.repository;

import com.portfoliomanager.model.Milestone;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(MilestoneRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class MilestoneRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private MilestoneRepository repository;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS milestones");
        jdbcTemplate.execute("""
                CREATE TABLE milestones (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    threshold_value_base DECIMAL(20,2) NOT NULL,
                    comparison_label VARCHAR(150) NOT NULL,
                    achieved BOOLEAN NOT NULL,
                    achieved_date DATE,
                    created_at TIMESTAMP
                )
                """);
    }

    @Test
    void saveAndFindById_roundTripPersistsValues() {
        Milestone input = Milestone.builder()
                .name("Luxury Car")
                .thresholdValueBase(new BigDecimal("5000000.00"))
                .comparisonLabel("Porsche")
                .achieved(false)
                .build();

        Milestone saved = repository.save(input);

        assertNotNull(saved.getId());
        assertEquals("Luxury Car", saved.getName());
        assertEquals(0, new BigDecimal("5000000.00").compareTo(saved.getThresholdValueBase()));
        assertFalse(saved.isAchieved());
    }

    @Test
    void findAll_returnsRowsSortedByThresholdAscending() {
        insertMilestone("High", "10000.00", false, null);
        insertMilestone("Low", "1000.00", false, null);
        insertMilestone("Mid", "5000.00", true, LocalDate.of(2025, 2, 2));

        List<Milestone> milestones = repository.findAll();

        assertEquals(3, milestones.size());
        assertEquals("Low", milestones.get(0).getName());
        assertEquals("Mid", milestones.get(1).getName());
        assertEquals("High", milestones.get(2).getName());
    }

    @Test
    void markAchieved_setsAchievedTrueAndDate() {
        long id = insertMilestone("Target", "1000.00", false, null);
        LocalDate achievedDate = LocalDate.of(2026, 8, 5);

        repository.markAchieved(id, achievedDate);

        Milestone updated = repository.findById(id).orElseThrow();
        assertTrue(updated.isAchieved());
        assertEquals(achievedDate, updated.getAchievedDate());
    }

    @Test
    void deleteById_returnsTrueWhenDeletedAndFalseWhenMissing() {
        long id = insertMilestone("Target", "1000.00", false, null);

        assertTrue(repository.deleteById(id));
        assertFalse(repository.deleteById(id));
    }

    @Test
    void findById_returnsEmptyWhenMissing() {
        assertTrue(repository.findById(9999L).isEmpty());
    }

    private long insertMilestone(String name, String threshold, boolean achieved, LocalDate achievedDate) {
        jdbcTemplate.update("""
                INSERT INTO milestones (name, threshold_value_base, comparison_label, achieved, achieved_date, created_at)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                name,
                new BigDecimal(threshold),
                name + " label",
                achieved,
                achievedDate,
                null);

        Long id = jdbcTemplate.queryForObject("SELECT MAX(id) FROM milestones", Long.class);
        return id == null ? -1 : id;
    }
}
