package com.portfoliomanager.repository;

import com.portfoliomanager.model.PortfolioSnapshot;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@JdbcTest
@Import(PortfolioSnapshotRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class PortfolioSnapshotRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PortfolioSnapshotRepository repository;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS portfolio_snapshots");
        jdbcTemplate.execute("""
                CREATE TABLE portfolio_snapshots (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    snapshot_date DATE NOT NULL UNIQUE,
                    total_invested_base DECIMAL(20,6) NOT NULL,
                    total_value_base DECIMAL(20,6) NOT NULL,
                    realized_pl_base DECIMAL(20,6) NOT NULL,
                    unrealized_pl_base DECIMAL(20,6) NOT NULL,
                    created_at TIMESTAMP
                )
                """);
    }

    @Test
    void findAll_returnsSnapshotsSortedByDateAscending() {
        insertSnapshot("2026-08-03", "1000", "1200", "20", "180");
        insertSnapshot("2026-08-01", "900", "1000", "10", "90");
        insertSnapshot("2026-08-02", "950", "1100", "15", "135");

        List<PortfolioSnapshot> all = repository.findAll();

        assertEquals(3, all.size());
        assertEquals(LocalDate.of(2026, 8, 1), all.get(0).getSnapshotDate());
        assertEquals(LocalDate.of(2026, 8, 2), all.get(1).getSnapshotDate());
        assertEquals(LocalDate.of(2026, 8, 3), all.get(2).getSnapshotDate());
    }

    @Test
    void findBetween_returnsOnlyRangeSortedAscending() {
        insertSnapshot("2026-08-01", "900", "1000", "10", "90");
        insertSnapshot("2026-08-02", "950", "1100", "15", "135");
        insertSnapshot("2026-08-03", "1000", "1200", "20", "180");

        List<PortfolioSnapshot> result = repository.findBetween(LocalDate.of(2026, 8, 2), LocalDate.of(2026, 8, 3));

        assertEquals(2, result.size());
        assertEquals(LocalDate.of(2026, 8, 2), result.get(0).getSnapshotDate());
        assertEquals(LocalDate.of(2026, 8, 3), result.get(1).getSnapshotDate());
    }

    @Test
    void upsert_insertsWhenDateMissing() {
        PortfolioSnapshot snapshot = snapshot(LocalDate.of(2026, 8, 5), "1500", "1800", "40", "260");

        repository.upsert(snapshot);

        assertEquals(1, countRows());
        PortfolioSnapshot stored = repository.findAll().get(0);
        assertEquals(LocalDate.of(2026, 8, 5), stored.getSnapshotDate());
        assertEquals(0, new BigDecimal("1800.000000").compareTo(stored.getTotalValueBase()));
    }

    @Test
    void upsert_updatesExistingRowForSameDate() {
        insertSnapshot("2026-08-05", "1500", "1800", "40", "260");

        PortfolioSnapshot updated = snapshot(LocalDate.of(2026, 8, 5), "1600", "2000", "50", "350");
        repository.upsert(updated);

        assertEquals(1, countRows());
        PortfolioSnapshot stored = repository.findAll().get(0);
        assertEquals(0, new BigDecimal("1600.000000").compareTo(stored.getTotalInvestedBase()));
        assertEquals(0, new BigDecimal("2000.000000").compareTo(stored.getTotalValueBase()));
        assertEquals(0, new BigDecimal("50.000000").compareTo(stored.getRealizedPlBase()));
        assertEquals(0, new BigDecimal("350.000000").compareTo(stored.getUnrealizedPlBase()));
    }

    private void insertSnapshot(String date,
                                String invested,
                                String value,
                                String realized,
                                String unrealized) {
        jdbcTemplate.update("""
                INSERT INTO portfolio_snapshots
                (snapshot_date, total_invested_base, total_value_base, realized_pl_base, unrealized_pl_base, created_at)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                LocalDate.parse(date),
                new BigDecimal(invested),
                new BigDecimal(value),
                new BigDecimal(realized),
                new BigDecimal(unrealized),
                null);
    }

    private PortfolioSnapshot snapshot(LocalDate date,
                                       String invested,
                                       String value,
                                       String realized,
                                       String unrealized) {
        return PortfolioSnapshot.builder()
                .snapshotDate(date)
                .totalInvestedBase(new BigDecimal(invested))
                .totalValueBase(new BigDecimal(value))
                .realizedPlBase(new BigDecimal(realized))
                .unrealizedPlBase(new BigDecimal(unrealized))
                .build();
    }

    private int countRows() {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM portfolio_snapshots", Integer.class);
        return count == null ? 0 : count;
    }
}
