package com.portfoliomanager.repository;

import com.portfoliomanager.model.PortfolioSnapshot;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@JdbcTest(properties = "spring.flyway.enabled=false")
@Import(PortfolioSnapshotRepository.class)
class PortfolioSnapshotRepositoryIntegrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PortfolioSnapshotRepository portfolioSnapshotRepository;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS portfolio_snapshots");
        jdbcTemplate.execute("""
                CREATE TABLE portfolio_snapshots (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    snapshot_date DATE NOT NULL UNIQUE,
                    total_invested_base DECIMAL(20,6) NOT NULL,
                    total_value_base DECIMAL(20,6) NOT NULL,
                    realized_pl_base DECIMAL(20,6) NOT NULL,
                    unrealized_pl_base DECIMAL(20,6) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void upsert_insertsWhenDateMissing() {
        PortfolioSnapshot snapshot = PortfolioSnapshot.builder()
                .snapshotDate(LocalDate.of(2026, 8, 1))
                .totalInvestedBase(new BigDecimal("1000.000000"))
                .totalValueBase(new BigDecimal("1100.000000"))
                .realizedPlBase(new BigDecimal("50.000000"))
                .unrealizedPlBase(new BigDecimal("100.000000"))
                .build();

        portfolioSnapshotRepository.upsert(snapshot);

        List<PortfolioSnapshot> all = portfolioSnapshotRepository.findAll();
        assertEquals(1, all.size());
        assertEquals(new BigDecimal("1100.000000"), all.get(0).getTotalValueBase());
    }

    @Test
    void upsert_updatesWhenDateExists() {
        jdbcTemplate.update(
                """
                        INSERT INTO portfolio_snapshots (
                            snapshot_date, total_invested_base, total_value_base, realized_pl_base, unrealized_pl_base, created_at
                        ) VALUES (?,?,?,?,?,?)
                        """,
                java.sql.Date.valueOf("2026-08-01"), new BigDecimal("1000.000000"), new BigDecimal("1100.000000"),
                new BigDecimal("10.000000"), new BigDecimal("100.000000"),
                java.sql.Timestamp.valueOf("2026-08-01 10:00:00"));

        PortfolioSnapshot updated = PortfolioSnapshot.builder()
                .snapshotDate(LocalDate.of(2026, 8, 1))
                .totalInvestedBase(new BigDecimal("1200.000000"))
                .totalValueBase(new BigDecimal("1400.000000"))
                .realizedPlBase(new BigDecimal("40.000000"))
                .unrealizedPlBase(new BigDecimal("200.000000"))
                .build();

        portfolioSnapshotRepository.upsert(updated);

        List<PortfolioSnapshot> all = portfolioSnapshotRepository.findAll();
        assertEquals(1, all.size());
        assertEquals(new BigDecimal("1200.000000"), all.get(0).getTotalInvestedBase());
        assertEquals(new BigDecimal("1400.000000"), all.get(0).getTotalValueBase());
    }

    @Test
    void findBetween_returnsAscendingRange() {
        jdbcTemplate.update(
                """
                        INSERT INTO portfolio_snapshots (
                            snapshot_date, total_invested_base, total_value_base, realized_pl_base, unrealized_pl_base, created_at
                        ) VALUES (?,?,?,?,?,?)
                        """,
                java.sql.Date.valueOf("2026-08-01"), new BigDecimal("1000.000000"), new BigDecimal("1100.000000"),
                new BigDecimal("10.000000"), new BigDecimal("100.000000"),
                java.sql.Timestamp.valueOf("2026-08-01 10:00:00"));
        jdbcTemplate.update(
                """
                        INSERT INTO portfolio_snapshots (
                            snapshot_date, total_invested_base, total_value_base, realized_pl_base, unrealized_pl_base, created_at
                        ) VALUES (?,?,?,?,?,?)
                        """,
                java.sql.Date.valueOf("2026-08-03"), new BigDecimal("1000.000000"), new BigDecimal("1300.000000"),
                new BigDecimal("20.000000"), new BigDecimal("300.000000"),
                java.sql.Timestamp.valueOf("2026-08-03 10:00:00"));
        jdbcTemplate.update(
                """
                        INSERT INTO portfolio_snapshots (
                            snapshot_date, total_invested_base, total_value_base, realized_pl_base, unrealized_pl_base, created_at
                        ) VALUES (?,?,?,?,?,?)
                        """,
                java.sql.Date.valueOf("2026-08-02"), new BigDecimal("1000.000000"), new BigDecimal("1200.000000"),
                new BigDecimal("15.000000"), new BigDecimal("200.000000"),
                java.sql.Timestamp.valueOf("2026-08-02 10:00:00"));

        List<PortfolioSnapshot> range = portfolioSnapshotRepository.findBetween(
                LocalDate.of(2026, 8, 2), LocalDate.of(2026, 8, 3));

        assertEquals(2, range.size());
        assertEquals(LocalDate.of(2026, 8, 2), range.get(0).getSnapshotDate());
        assertEquals(LocalDate.of(2026, 8, 3), range.get(1).getSnapshotDate());
    }
}
