package com.portfoliomanager.repository;

import com.portfoliomanager.model.Transaction;
import com.portfoliomanager.model.TransactionType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@JdbcTest(properties = "spring.flyway.enabled=false")
@Import(TransactionRepository.class)
class TransactionRepositoryIntegrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private TransactionRepository transactionRepository;

    @BeforeEach
    void setUpSchemaAndData() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS transactions");
        jdbcTemplate.execute("DROP TABLE IF EXISTS investments");
        jdbcTemplate.execute("""
                CREATE TABLE investments (
                    id BIGINT PRIMARY KEY,
                    user_id BIGINT NOT NULL
                )
                """);
        jdbcTemplate.update("INSERT INTO investments (id, user_id) VALUES (?, ?)", 1L, 1L);
        jdbcTemplate.execute("""
                CREATE TABLE transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    investment_id BIGINT NOT NULL,
                    type VARCHAR(10) NOT NULL,
                    quantity DECIMAL(20,6) NULL,
                    price DECIMAL(20,6) NULL,
                    amount DECIMAL(20,6) NOT NULL,
                    realized_pl DECIMAL(20,6) NULL,
                    currency VARCHAR(3) NOT NULL,
                    transaction_date DATE NOT NULL,
                    notes VARCHAR(255) NULL,
                    created_at TIMESTAMP NOT NULL
                )
                """);

        jdbcTemplate.update(
                """
                        INSERT INTO transactions (
                            investment_id, type, quantity, price, amount, realized_pl, currency, transaction_date, notes, created_at
                        ) VALUES (?,?,?,?,?,?,?,?,?,?)
                        """,
                1L, "SELL", new BigDecimal("2.000000"), new BigDecimal("110.000000"),
                new BigDecimal("220.000000"), new BigDecimal("20.000000"), "USD",
                java.sql.Date.valueOf("2026-08-03"), "realized", java.sql.Timestamp.valueOf("2026-08-03 10:00:00"));

        jdbcTemplate.update(
                """
                        INSERT INTO transactions (
                            investment_id, type, quantity, price, amount, realized_pl, currency, transaction_date, notes, created_at
                        ) VALUES (?,?,?,?,?,?,?,?,?,?)
                        """,
                1L, "SELL", new BigDecimal("1.000000"), new BigDecimal("100.000000"),
                new BigDecimal("100.000000"), null, "USD",
                java.sql.Date.valueOf("2026-08-02"), "no realized pl",
                java.sql.Timestamp.valueOf("2026-08-02 10:00:00"));

        jdbcTemplate.update(
                """
                        INSERT INTO transactions (
                            investment_id, type, quantity, price, amount, realized_pl, currency, transaction_date, notes, created_at
                        ) VALUES (?,?,?,?,?,?,?,?,?,?)
                        """,
                1L, "BUY", new BigDecimal("3.000000"), new BigDecimal("90.000000"),
                new BigDecimal("270.000000"), new BigDecimal("5.000000"), "USD",
                java.sql.Date.valueOf("2026-08-01"), "buy", java.sql.Timestamp.valueOf("2026-08-01 10:00:00"));
    }

    @Test
    void findAllRealizedPlTransactions_returnsOnlySellWithNonNullRealizedPl() {
        List<Transaction> realized = transactionRepository.findAllRealizedPlTransactions(1L);

        assertEquals(1, realized.size());
        Transaction tx = realized.get(0);
        assertEquals(TransactionType.SELL, tx.getType());
        assertEquals(new BigDecimal("20.000000"), tx.getRealizedPl());
        assertEquals("USD", tx.getCurrency());
        assertEquals(LocalDate.of(2026, 8, 3), tx.getTransactionDate());
    }
}
