package com.portfoliomanager.repository;

import com.portfoliomanager.model.Transaction;
import com.portfoliomanager.model.TransactionType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(TransactionRepository.class)
@TestPropertySource(properties = "spring.flyway.enabled=false")
class TransactionRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private TransactionRepository repository;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS transactions");
        jdbcTemplate.execute("""
                CREATE TABLE transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    investment_id BIGINT NOT NULL,
                    type VARCHAR(10) NOT NULL,
                    quantity DECIMAL(20,6),
                    price DECIMAL(20,6),
                    amount DECIMAL(20,6) NOT NULL,
                    realized_pl DECIMAL(20,6),
                    currency VARCHAR(3) NOT NULL,
                    transaction_date DATE NOT NULL,
                    notes VARCHAR(255),
                    created_at TIMESTAMP
                )
                """);
    }

    @Test
    void saveAndFindById_roundTripPersistsValues() {
        Transaction input = Transaction.builder()
                .investmentId(10L)
                .type(TransactionType.BUY)
                .quantity(new BigDecimal("2.000000"))
                .price(new BigDecimal("120.000000"))
                .amount(new BigDecimal("240.000000"))
                .realizedPl(null)
                .currency("USD")
                .transactionDate(LocalDate.of(2026, 8, 5))
                .notes("buy")
                .build();

        Transaction saved = repository.save(input);

        assertNotNull(saved.getId());
        assertEquals(TransactionType.BUY, saved.getType());
        assertEquals(0, new BigDecimal("240.000000").compareTo(saved.getAmount()));
        assertEquals("USD", saved.getCurrency());
    }

    @Test
    void findByInvestmentId_ordersByDateDescThenIdDesc() {
        long id1 = insertTx(10L, "BUY", "2026-08-01", "100.000000", null);
        long id2 = insertTx(10L, "SELL", "2026-08-05", "120.000000", "20.000000");
        long id3 = insertTx(10L, "BUY", "2026-08-05", "130.000000", null);

        List<Transaction> results = repository.findByInvestmentId(10L);

        assertEquals(3, results.size());
        assertEquals(id3, results.get(0).getId());
        assertEquals(id2, results.get(1).getId());
        assertEquals(id1, results.get(2).getId());
    }

    @Test
    void findAll_ordersByDateDescThenIdDescAcrossInvestments() {
        long id1 = insertTx(10L, "BUY", "2026-08-01", "100.000000", null);
        long id2 = insertTx(11L, "SELL", "2026-08-04", "140.000000", "10.000000");
        long id3 = insertTx(12L, "BUY", "2026-08-04", "150.000000", null);

        List<Transaction> results = repository.findAll();

        assertEquals(3, results.size());
        assertEquals(id3, results.get(0).getId());
        assertEquals(id2, results.get(1).getId());
        assertEquals(id1, results.get(2).getId());
    }

    @Test
    void findAllRealizedPlTransactions_returnsOnlySellRowsWithRealizedPl() {
        insertTx(10L, "BUY", "2026-08-01", "100.000000", null);
        insertTx(10L, "SELL", "2026-08-02", "120.000000", null);
        long sellWithPl = insertTx(10L, "SELL", "2026-08-03", "130.000000", "30.000000");

        List<Transaction> realized = repository.findAllRealizedPlTransactions();

        assertEquals(1, realized.size());
        assertEquals(sellWithPl, realized.get(0).getId());
        assertEquals(TransactionType.SELL, realized.get(0).getType());
        assertEquals(0, new BigDecimal("30.000000").compareTo(realized.get(0).getRealizedPl()));
    }

    @Test
    void deleteById_returnsTrueThenFalse() {
        long id = insertTx(10L, "BUY", "2026-08-01", "100.000000", null);

        assertTrue(repository.deleteById(id));
        assertFalse(repository.deleteById(id));
    }

    private long insertTx(Long investmentId,
                          String type,
                          String transactionDate,
                          String amount,
                          String realizedPl) {
        jdbcTemplate.update("""
                INSERT INTO transactions
                (investment_id, type, quantity, price, amount, realized_pl, currency, transaction_date, notes, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                investmentId,
                type,
                new BigDecimal("1.000000"),
                new BigDecimal("100.000000"),
                new BigDecimal(amount),
                realizedPl == null ? null : new BigDecimal(realizedPl),
                "USD",
                LocalDate.parse(transactionDate),
                "note",
                null);

        Long id = jdbcTemplate.queryForObject("SELECT MAX(id) FROM transactions", Long.class);
        return id == null ? -1 : id;
    }
}
